
export const ACTIVITY_INDICATOR = 'ACTIVITY_INDICATOR';
export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_SUCCESS';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const API_STATUS = 'API_STATUS';
export const OPEN_PRODUCT_POPUP = 'OPEN_PRODUCT_POPUP'; 
export const DELETE_PRODUCT = 'DELETE_PRODUCT';